/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TableComponent {
        "headers": string;
        "items": string;
        "sortAscending": boolean;
        "sortColumn": string;
    }
}
declare global {
    interface HTMLTableComponentElement extends Components.TableComponent, HTMLStencilElement {
    }
    var HTMLTableComponentElement: {
        prototype: HTMLTableComponentElement;
        new (): HTMLTableComponentElement;
    };
    interface HTMLElementTagNameMap {
        "table-component": HTMLTableComponentElement;
    }
}
declare namespace LocalJSX {
    interface TableComponent {
        "headers"?: string;
        "items"?: string;
        "sortAscending"?: boolean;
        "sortColumn"?: string;
    }
    interface IntrinsicElements {
        "table-component": TableComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "table-component": LocalJSX.TableComponent & JSXBase.HTMLAttributes<HTMLTableComponentElement>;
        }
    }
}
